"""First migration

Revision ID: 70485fb3f5b1
Revises: 
Create Date: 2025-04-02 14:40:03.386579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70485fb3f5b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sql_query_logs')
    op.drop_table('article')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('pagepath', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('pubdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('wp_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('wp_publication_tags', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wp_post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wp_post_views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yoast_focus_keyword', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('yoast_metadesc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('yoast_seo_score', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('yoast_content_readability_score', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('yoast_keyword_synonyms', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('yoast_estimated_reading_time', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('ga4_views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ga4_active_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ga4_views_per_active_user', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ga4_avg_engagement_time_per_active_user', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ga4_sessions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ga4_new_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ga4_new_core_readers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ga4_avg_engagement_duration_per_session', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='article_pkey'),
    sa.UniqueConstraint('pagepath', name='article_pagepath_key')
    )
    op.create_table('sql_query_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('execution_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sql_query_logs_pkey')
    )
    # ### end Alembic commands ###
